# Generated by Django 6.0.7 on 2026-07-24 12:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('retired', 'Dado de baja')], default='active', max_length=8)),
                ('acquired_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('tractor', 'Tractor'), ('harvester', 'Cosechadora'), ('mixer', 'Mixer'), ('truck', 'Camión'), ('other', 'Otro')], default='other', max_length=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='clients.client')),
            ],
            options={
                'ordering': ['client', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('preventive', 'Preventivo'), ('corrective', 'Correctivo'), ('other', 'Otro')], default='preventive', max_length=12)),
                ('title', models.CharField(max_length=120)),
                ('hours', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_events', to='machinery.machine')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['client', 'date'], name='machinery_m_client__2ea81c_idx'), models.Index(fields=['machine', 'date'], name='machinery_m_machine_74131e_idx')],
            },
        ),
    ]
