# Generated by Django 6.0.7 on 2026-07-25 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('unit', models.CharField(default='unit', max_length=16)),
                ('category', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InputStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_kind', models.CharField(choices=[('own', 'Feedlot (propio)'), ('client', 'Cliente')], default='own', max_length=8)),
                ('direction', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('source_kind', models.CharField(blank=True, max_length=32)),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='input_stock', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('input_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inputtype')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['owner_kind', 'client', 'input_type'], name='inventory_i_owner_k_8e5331_idx')],
            },
        ),
    ]
