# Generated by Django 6.0.7 on 2026-07-29 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('livestock', '0004_lot_unique_lot_code_per_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IatfProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Weaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weaning_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('purpose', models.CharField(choices=[('replacement', 'Reposición'), ('sale', 'Venta'), ('undecided', 'Sin definir')], default='undecided', max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Calving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('live', 'Vivo'), ('stillborn', 'Muerto al nacer'), ('aborted', 'Aborto')], max_length=10)),
                ('calving_ease', models.CharField(choices=[('normal', 'Normal'), ('assisted', 'Asistido'), ('caesarean', 'Cesárea')], default='normal', max_length=10)),
                ('calf_sex', models.CharField(blank=True, max_length=6)),
                ('calf_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('births_count', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='livestock.animal')),
                ('calf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='birth_calving', to='livestock.animal')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calvings', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='livestock.lot')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IatfProtocolStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_offset', models.IntegerField()),
                ('action', models.CharField(max_length=200)),
                ('product', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='breeding.iatfprotocol')),
            ],
            options={
                'ordering': ['protocol', 'day_offset', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PregnancyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('palpation', 'Palpación'), ('ultrasound', 'Ecografía'), ('blood', 'Sangre')], max_length=12)),
                ('result', models.CharField(choices=[('pregnant', 'Preñada'), ('empty', 'Vacía'), ('uncertain', 'Dudosa')], max_length=10)),
                ('gestation_days', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='livestock.animal')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pregnancy_checks', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='livestock.lot')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('natural', 'Servicio natural'), ('ai', 'Inseminación artificial'), ('iatf', 'IATF'), ('embryo_transfer', 'Transferencia embrionaria')], max_length=16)),
                ('service_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='livestock.animal')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breeding_services', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
            },
        ),
    ]
