# Generated by Django 6.0.7 on 2026-07-29 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeding', '0001_initial'),
        ('clients', '0001_initial'),
        ('genetics', '0001_initial'),
        ('livestock', '0004_lot_unique_lot_code_per_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='embryo_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='genetics.embryobatch'),
        ),
        migrations.AddField(
            model_name='service',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='livestock.lot'),
        ),
        migrations.AddField(
            model_name='service',
            name='protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='breeding.iatfprotocol'),
        ),
        migrations.AddField(
            model_name='service',
            name='semen_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='genetics.semenbatch'),
        ),
        migrations.AddField(
            model_name='service',
            name='sire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='genetics.sire'),
        ),
        migrations.AddField(
            model_name='pregnancycheck',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pregnancy_checks', to='breeding.service'),
        ),
        migrations.AddField(
            model_name='calving',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calvings', to='breeding.service'),
        ),
        migrations.AddField(
            model_name='weaning',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='livestock.animal'),
        ),
        migrations.AddField(
            model_name='weaning',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weanings', to='clients.client'),
        ),
        migrations.AddField(
            model_name='weaning',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weaning',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='livestock.lot'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('animal__isnull', False), ('lot__isnull', True)), models.Q(('animal__isnull', True), ('lot__isnull', False)), _connector='OR'), name='service_target_animal_xor_lot'),
        ),
        migrations.AddConstraint(
            model_name='pregnancycheck',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('animal__isnull', False), ('lot__isnull', True)), models.Q(('animal__isnull', True), ('lot__isnull', False)), _connector='OR'), name='pregnancycheck_target_animal_xor_lot'),
        ),
        migrations.AddConstraint(
            model_name='calving',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('animal__isnull', False), ('lot__isnull', True)), models.Q(('animal__isnull', True), ('lot__isnull', False)), _connector='OR'), name='calving_target_animal_xor_lot'),
        ),
        migrations.AddConstraint(
            model_name='weaning',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('animal__isnull', False), ('lot__isnull', True)), models.Q(('animal__isnull', True), ('lot__isnull', False)), _connector='OR'), name='weaning_target_animal_xor_lot'),
        ),
    ]
