# Generated by Django 6.0.7 on 2026-07-25 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0002_death_exit_weighing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renspa', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('holder', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Caravana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_number', models.CharField(max_length=40, unique=True)),
                ('assigned_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caravanas', to='livestock.animal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_date', '-id'],
                'indexes': [models.Index(fields=['animal'], name='traceabilit_animal__15693d_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransitDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dte_number', models.CharField(max_length=40, unique=True)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('cow', 'Vaca'), ('bull', 'Toro'), ('steer', 'Novillo'), ('heifer', 'Vaquillona'), ('calf', 'Ternero/a'), ('mixed', 'Mixto')], default='mixed', max_length=8)),
                ('head_count', models.PositiveIntegerField()),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transits_in', to='traceability.establishment')),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transits', to='livestock.lot')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transits_out', to='traceability.establishment')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['origin', 'destination', '-date'], name='traceabilit_origin__b1dc47_idx')],
            },
        ),
    ]
