# Generated by Django 5.2.16 on 2026-07-21 16:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("anonymous", "Anónimo (cabezas + kg)"),
                            ("named", "Nominado (agrupa animales)"),
                        ],
                        default="anonymous",
                        max_length=12,
                    ),
                ),
                ("head_count", models.PositiveIntegerField(default=0)),
                (
                    "total_weight",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activo"), ("closed", "Cerrado")],
                        default="active",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "ordering": ["client", "code"],
            },
        ),
        migrations.CreateModel(
            name="Intake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("individual", "Individual"), ("lot", "Lote")],
                        max_length=12,
                    ),
                ),
                ("head_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "total_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intakes",
                        to="clients.client",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="livestock.lot",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ear_tag", models.CharField(max_length=40)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cow", "Vaca"),
                            ("bull", "Toro"),
                            ("steer", "Novillo"),
                            ("heifer", "Vaquillona"),
                            ("calf", "Ternero/a"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Macho"), ("female", "Hembra")],
                        max_length=6,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("dead", "Muerto"),
                            ("sold", "Vendido"),
                            ("exited", "Egresado"),
                        ],
                        default="active",
                        max_length=8,
                    ),
                ),
                ("entry_date", models.DateField()),
                (
                    "entry_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "current_weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="animals",
                        to="clients.client",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="animals",
                        to="livestock.lot",
                    ),
                ),
            ],
            options={
                "ordering": ["client", "ear_tag"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("client", "ear_tag"),
                        name="unique_active_ear_tag_per_client",
                    )
                ],
            },
        ),
    ]
