# Generated by Django 5.2.16 on 2026-07-21 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Death',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cause', models.CharField(choices=[('disease', 'Enfermedad'), ('accident', 'Accidente'), ('unknown', 'Desconocida'), ('other', 'Otra')], default='unknown', max_length=10)),
                ('cause_detail', models.CharField(blank=True, max_length=255)),
                ('head_count', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='livestock.animal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='livestock.lot')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('animal__isnull', False), ('lot__isnull', True)), models.Q(('animal__isnull', True), ('lot__isnull', False)), _connector='OR'), name='death_target_animal_xor_lot')],
            },
        ),
        migrations.CreateModel(
            name='Exit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('sale', 'Venta'), ('transfer', 'Retiro'), ('other', 'Otro')], default='sale', max_length=10)),
                ('destination', models.CharField(blank=True, max_length=120)),
                ('head_count', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sale_price_per_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='livestock.animal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='livestock.lot')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('animal__isnull', False), ('lot__isnull', True)), models.Q(('animal__isnull', True), ('lot__isnull', False)), _connector='OR'), name='exit_target_animal_xor_lot')],
            },
        ),
        migrations.CreateModel(
            name='Weighing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=12)),
                ('head_count', models.PositiveIntegerField(blank=True, null=True)),
                ('method', models.CharField(choices=[('scale', 'Báscula'), ('estimated', 'Estimado')], default='scale', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='livestock.animal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='livestock.lot')),
            ],
            options={
                'ordering': ['date', 'id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('animal__isnull', False), ('lot__isnull', True)), models.Q(('animal__isnull', True), ('lot__isnull', False)), _connector='OR'), name='weighing_target_animal_xor_lot')],
            },
        ),
    ]
