# Generated by Django 6.0.7 on 2026-07-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_death_exit_weighing'),
    ]

    operations = [
        migrations.AddField(
            model_name='exit',
            name='engorde_commission_pct',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
