# Generated by Django 6.0.7 on 2026-07-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('livestock', '0003_exit_engorde_commission_pct'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(fields=('client', 'code'), name='unique_lot_code_per_client'),
        ),
    ]
