# Generated by Django 6.0.7 on 2026-07-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admins_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.URLField(blank=True),
        ),
    ]
