# Generated by Django 6.0.7 on 2026-07-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
