# Generated by Django 6.0.7 on 2026-07-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar_visible_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
