/* LIVE-DOC:START — alvs-feedlot-campo live-doc; see [[adr-17-live-doc-backlinks]]
 * Governed by: [[adr-52-frontend-and-design-system]]
 * Docs: [[FRONTEND]]
 * LIVE-DOC:END */

export type GalleryHydration = "none" | "load" | "visible" | "idle";

export interface GalleryRegistryEntry {
  path: string;
  category: string;
  hydration: GalleryHydration;
}

export const GALLERY_REGISTRY: GalleryRegistryEntry[] = [
  { path: "primitives/CornerNavTriangle.svelte", category: "primitives", hydration: "none" },
  { path: "primitives/HomeTriangle.svelte", category: "primitives", hydration: "none" },
  { path: "primitives/PageStage.svelte", category: "primitives", hydration: "none" },
  { path: "primitives/titles/PageHeader.svelte", category: "primitives", hydration: "none" },
  { path: "primitives/titles/PageTitle.svelte", category: "primitives", hydration: "none" },
  { path: "primitives/titles/SectionTitle.svelte", category: "primitives", hydration: "none" },
  { path: "data/ChipFilterBar.svelte", category: "data", hydration: "load" },
  { path: "data/Collapsible.svelte", category: "data", hydration: "visible" },
  { path: "data/DataTable.svelte", category: "data", hydration: "load" },
  { path: "data/NumericValue.svelte", category: "data", hydration: "none" },
  { path: "data/Pagination.svelte", category: "data", hydration: "load" },
  { path: "data/StatusBadge.svelte", category: "data", hydration: "none" },
  { path: "data/Tree.svelte", category: "data", hydration: "visible" },
  { path: "dashboard/ChoiceList.svelte", category: "dashboard", hydration: "visible" },
  { path: "dashboard/EntityCard.svelte", category: "dashboard", hydration: "none" },
  { path: "dashboard/EntityGrid.svelte", category: "dashboard", hydration: "visible" },
  { path: "dashboard/MetricTile.svelte", category: "dashboard", hydration: "none" },
  { path: "dashboard/MetricTileStrip.svelte", category: "dashboard", hydration: "visible" },
  { path: "dashboard/SummaryCard.svelte", category: "dashboard", hydration: "none" },
  { path: "form/Calendar.svelte", category: "form", hydration: "visible" },
  { path: "form/Checkbox.svelte", category: "form", hydration: "visible" },
  { path: "form/Combobox.svelte", category: "form", hydration: "visible" },
  { path: "form/DatePicker.svelte", category: "form", hydration: "visible" },
  { path: "form/DateRangePicker.svelte", category: "form", hydration: "visible" },
  { path: "form/PinInput.svelte", category: "form", hydration: "visible" },
  { path: "form/RangeCalendar.svelte", category: "form", hydration: "visible" },
  { path: "form/Select.svelte", category: "form", hydration: "visible" },
  { path: "form/Slider.svelte", category: "form", hydration: "visible" },
  { path: "form/Switch.svelte", category: "form", hydration: "visible" },
  { path: "form/TagsInput.svelte", category: "form", hydration: "visible" },
  { path: "form/ToggleGroup.svelte", category: "form", hydration: "visible" },
  { path: "nav/Breadcrumb.svelte", category: "nav", hydration: "visible" },
  { path: "nav/ContextMenu.svelte", category: "nav", hydration: "visible" },
  { path: "nav/DropdownMenu.svelte", category: "nav", hydration: "visible" },
  { path: "nav/Menubar.svelte", category: "nav", hydration: "visible" },
  { path: "nav/TableOfContents.svelte", category: "nav", hydration: "visible" },
  { path: "nav/Tabs.svelte", category: "nav", hydration: "visible" },
  { path: "chat/ChatComposer.svelte", category: "chat", hydration: "none" },
  { path: "chat/ChatMessageList.svelte", category: "chat", hydration: "none" },
  { path: "chat/ChatUI.svelte", category: "chat", hydration: "visible" },
  { path: "overlay/Accordion.svelte", category: "overlay", hydration: "visible" },
  { path: "overlay/ConfirmDialog.svelte", category: "overlay", hydration: "none" },
  { path: "overlay/Dialog.svelte", category: "overlay", hydration: "visible" },
  { path: "overlay/Drawer.svelte", category: "overlay", hydration: "visible" },
  { path: "overlay/FancyDrawer.svelte", category: "overlay", hydration: "visible" },
  { path: "overlay/HoverCard.svelte", category: "overlay", hydration: "visible" },
  { path: "overlay/Popover.svelte", category: "overlay", hydration: "visible" },
  { path: "overlay/ScrollArea.svelte", category: "overlay", hydration: "visible" },
  { path: "overlay/SidePanel.svelte", category: "overlay", hydration: "visible" },
  { path: "overlay/Tooltip.svelte", category: "overlay", hydration: "visible" },
  { path: "feedback/Progress.svelte", category: "feedback", hydration: "visible" },
  { path: "feedback/Toast.svelte", category: "feedback", hydration: "idle" },
  { path: "auth/AuthPanel.svelte", category: "auth", hydration: "visible" },
  { path: "auth/ProfileForm.svelte", category: "auth", hydration: "load" },
  { path: "auth/SessionBadge.svelte", category: "auth", hydration: "load" },
  { path: "auth/SessionMenuRow.svelte", category: "auth", hydration: "none" },
  { path: "theme/AppearanceCard.svelte", category: "theme", hydration: "load" },
  { path: "theme/PaletteFields.svelte", category: "theme", hydration: "none" },
  { path: "theme/QuickThemeToggle.svelte", category: "theme", hydration: "none" },
  { path: "theme/ThemeModeToggle.svelte", category: "theme", hydration: "visible" },
  { path: "shell/ChatDrawer.svelte", category: "shell", hydration: "load" },
  { path: "shell/NavBadge.svelte", category: "shell", hydration: "none" },
  { path: "shell/NavBrand.svelte", category: "shell", hydration: "none" },
  { path: "shell/NavGlyph.svelte", category: "shell", hydration: "none" },
  { path: "shell/NavItem.svelte", category: "shell", hydration: "none" },
  { path: "shell/NavLockToggle.svelte", category: "shell", hydration: "none" },
  { path: "shell/NavPanelTitle.svelte", category: "shell", hydration: "none" },
  { path: "shell/NavPendingBar.svelte", category: "shell", hydration: "none" },
  { path: "showcase/AccordionDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/AlertDialogDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/BreadcrumbDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/ButtonsBadgesDemo.svelte", category: "showcase", hydration: "none" },
  { path: "showcase/CalendarDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/ChoiceListDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/CollapsibleDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/ConfirmDialogDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/ContextMenuDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/CornerNavTriangleDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/DialogDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/DrawerDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/DropdownMenuDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/FancyDrawerDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/HomeTriangleDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/HoverCardDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/MenubarDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/PageHeaderDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/PaginationDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/PinInputDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/PopoverDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/ProgressDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/RangeCalendarDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/ScrollAreaDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/SidePanelDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/SliderDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/SlotCopy.svelte", category: "showcase", hydration: "none" },
  { path: "showcase/TableOfContentsDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/TabsDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/TagsInputDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/ToastTriggerDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/ToggleGroupDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/TooltipDemo.svelte", category: "showcase", hydration: "visible" },
  { path: "showcase/TreeDemo.svelte", category: "showcase", hydration: "visible" },
];
