# Generated by Django 6.0.7 on 2026-07-28 19:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('livestock', '0004_lot_unique_lot_code_per_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('labor', 'Mano de obra'), ('fuel', 'Combustible'), ('machinery', 'Maquinaria'), ('other', 'Otro')], default='other', max_length=12)),
                ('fuel_kind', models.CharField(blank=True, max_length=32)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='livestock.lot')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['client', 'date'], name='expenses_ex_client__7128cc_idx'), models.Index(fields=['category', 'date'], name='expenses_ex_categor_a62d07_idx')],
            },
        ),
    ]
