# Generated by Django 6.0.7 on 2026-07-24 12:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pivot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('retired', 'Dado de baja')], default='active', max_length=8)),
                ('acquired_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area_ha', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pivots', to='clients.client')),
            ],
            options={
                'ordering': ['client', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('alfalfa', 'Alfalfa'), ('other', 'Otro')], default='alfalfa', max_length=12)),
                ('sown_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Activo'), ('terminated', 'Terminado')], default='active', max_length=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pivot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crops', to='crops.pivot')),
            ],
            options={
                'ordering': ['-sown_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Cutting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kg_harvested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bales', models.PositiveIntegerField(blank=True, null=True)),
                ('quality', models.CharField(blank=True, choices=[('high', 'Alta'), ('medium', 'Media'), ('low', 'Baja')], max_length=8)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuttings', to='crops.crop')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['crop', 'date'], name='crops_cutti_crop_id_a6c8c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='FieldTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('sowing', 'Siembra'), ('fertilizing', 'Fertilización'), ('irrigation', 'Riego'), ('weeding', 'Control de malezas'), ('other', 'Otro')], default='other', max_length=12)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pivot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_tasks', to='crops.pivot')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['client', 'date'], name='crops_field_client__f0daeb_idx'), models.Index(fields=['pivot', 'date'], name='crops_field_pivot_i_435754_idx')],
            },
        ),
    ]
