# Generated by Django 6.0.7 on 2026-07-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_paymentallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='concept',
            field=models.CharField(choices=[('feeding', 'Alimentación'), ('health', 'Sanidad'), ('service', 'Servicio'), ('adjustment', 'Ajuste'), ('payment', 'Pago'), ('sale', 'Venta')], max_length=16),
        ),
    ]
