# Generated by Django 6.0.7 on 2026-07-25 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('capacity_head', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=8)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Ration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BunkScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.PositiveSmallIntegerField(help_text='Bunk-reading scale 0–4.')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bunk_scores', to='feedyard.pen')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['pen', 'date'], name='feedyard_bu_pen_id_b2928a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 4)), name='bunkscore_score_0_to_4')],
            },
        ),
        migrations.CreateModel(
            name='LoadingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('planned_as_fed_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loading_orders', to='feedyard.pen')),
                ('ration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loading_orders', to='feedyard.ration')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['pen', 'date'], name='feedyard_lo_pen_id_af1499_idx')],
            },
        ),
        migrations.CreateModel(
            name='RationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proportion', models.DecimalField(decimal_places=3, help_text='Percent, as-fed.', max_digits=6)),
                ('dry_matter_pct', models.DecimalField(decimal_places=3, max_digits=6)),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='feed.feedtype')),
                ('ration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='feedyard.ration')),
            ],
            options={
                'ordering': ['ration', 'id'],
                'constraints': [models.UniqueConstraint(fields=('ration', 'feed_type'), name='rationline_unique_feed_per_ration')],
            },
        ),
    ]
