# Generated by Django 6.0.7 on 2026-07-25 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedyard', '0001_initial'),
        ('livestock', '0002_death_exit_weighing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('direction', models.CharField(choices=[('in', 'Ingreso a corral'), ('out', 'Egreso de corral')], max_length=3)),
                ('head_count', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pen_placements', to='livestock.animal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pen_placements', to='livestock.lot')),
                ('pen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='feedyard.pen')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['pen', 'date'], name='feedyard_pe_pen_id_a8643c_idx'), models.Index(fields=['animal', 'date'], name='feedyard_pe_animal__f5f1ff_idx'), models.Index(fields=['lot', 'date'], name='feedyard_pe_lot_id_efdd69_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('animal__isnull', False), ('lot__isnull', True)), models.Q(('animal__isnull', True), ('lot__isnull', False)), _connector='OR'), name='penplacement_target_animal_xor_lot')],
            },
        ),
    ]
