# Generated by Django 5.2.16 on 2026-07-23 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('kind', models.CharField(choices=[('market', 'Mercado físico'), ('index', 'Índice')], default='market', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_automated', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('price_avg', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('price_min', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('price_median', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('head_count', models.PositiveIntegerField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='market.marketsource')),
            ],
            options={
                'ordering': ['-date', 'source', 'category'],
                'indexes': [models.Index(fields=['source', 'date'], name='market_mark_source__f224de_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'category', 'date'), name='unique_price_per_source_category_date')],
            },
        ),
    ]
