# Generated by Django 5.2.16 on 2026-07-21 19:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('livestock', '0002_death_exit_weighing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('vaccine', 'Vacuna'), ('treatment', 'Tratamiento'), ('antiparasitic', 'Antiparasitario'), ('other', 'Otro')], default='vaccine', max_length=14)),
                ('unit', models.CharField(default='dosis', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('head_count', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('date', models.DateField()),
                ('applied_by', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='health_events', to='livestock.animal')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_events', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='health_events', to='livestock.lot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='sanitary.healthproduct')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['client', 'date'], name='sanitary_he_client__dfdd5f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('animal__isnull', False), ('lot__isnull', True)), models.Q(('animal__isnull', True), ('lot__isnull', False)), _connector='OR'), name='health_event_target_animal_xor_lot')],
            },
        ),
    ]
