# Generated by Django 6.0.7 on 2026-07-26 01:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('livestock', '0002_death_exit_weighing'),
        ('sanitary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SanitaryPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SanitaryPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_offset', models.PositiveIntegerField(default=0)),
                ('dose', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=120)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sanitary.sanitaryplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='sanitary.healthproduct')),
            ],
            options={
                'ordering': ['day_offset', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PlanEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_enrollments', to='livestock.animal')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_enrollments', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_enrollments', to='livestock.lot')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='sanitary.sanitaryplan')),
            ],
            options={
                'ordering': ['-start_date', '-id'],
                'indexes': [models.Index(fields=['client', 'start_date'], name='sanitary_pl_client__b097d2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('animal__isnull', False), ('lot__isnull', True)), models.Q(('animal__isnull', True), ('lot__isnull', False)), _connector='OR'), name='plan_enrollment_target_animal_xor_lot')],
            },
        ),
    ]
