# Generated by Django 6.0.7 on 2026-07-25 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(blank=True, max_length=120)),
                ('date', models.DateField()),
                ('rainfall_mm', models.DecimalField(decimal_places=1, default=0, max_digits=7)),
                ('temp_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temp_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['site', '-date'], name='weather_wea_site_8fcee3_idx')],
            },
        ),
    ]
