# Generated by Django 5.2.16 on 2026-07-23 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('livestock', 'Ganadero'), ('finance', 'Contable-financiero'), ('admin', 'Administrativo')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('system_prompt', models.TextField(help_text='Rol base del asesor. Configuración, no código.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='AdvisorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('output', models.TextField(blank=True)),
                ('model_id', models.CharField(blank=True, max_length=120)),
                ('tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='advisors.advisor')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advisor_reports', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['client', 'advisor', '-created_at'], name='advisors_ad_client__bc1be6_idx')],
            },
        ),
    ]
