# Generated by Django 6.0.7 on 2026-07-29 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('livestock', '0004_lot_unique_lot_code_per_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemenBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=80)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('tank', models.CharField(blank=True, max_length=80)),
                ('position', models.CharField(blank=True, max_length=80)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sire', 'batch_code'],
            },
        ),
        migrations.CreateModel(
            name='SemenSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('straws', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semen_purchases', to='clients.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semen_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='genetics.semenbatch')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Sire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('breed', models.CharField(blank=True, max_length=120)),
                ('registry_id', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sire_records', to='livestock.animal')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='semenbatch',
            name='sire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semen_batches', to='genetics.sire'),
        ),
        migrations.CreateModel(
            name='EmbryoFlush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('embryos_collected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('grade', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embryo_flushes', to='livestock.animal')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embryo_flushes', to='genetics.sire')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmbryoBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=40)),
                ('flush_date', models.DateField(blank=True, null=True)),
                ('tank', models.CharField(blank=True, max_length=80)),
                ('position', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='embryo_batches', to='livestock.animal')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embryo_batches', to='genetics.sire')),
            ],
            options={
                'ordering': ['donor', '-flush_date'],
            },
        ),
        migrations.CreateModel(
            name='BreedingValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait', models.CharField(choices=[('birth_weight', 'Peso al nacer'), ('weaning_weight', 'Peso al destete'), ('milk', 'Leche'), ('ribeye_area', 'Área de ojo de bife'), ('marbling', 'Marmoleo'), ('scrotal', 'Circunferencia escrotal'), ('other', 'Otro')], max_length=20)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breeding_values', to='genetics.sire')),
            ],
            options={
                'ordering': ['sire', 'trait', '-date'],
            },
        ),
        migrations.CreateModel(
            name='EmbryoMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('collection', 'Colecta'), ('transfer', 'Transferencia'), ('sale', 'Venta'), ('discard', 'Descarte'), ('adjustment', 'Ajuste')], max_length=16)),
                ('date', models.DateField()),
                ('source_kind', models.CharField(blank=True, max_length=40)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('embryo_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='genetics.embryobatch')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['embryo_batch', 'date'], name='genetics_em_embryo__ab3129_idx')],
            },
        ),
        migrations.CreateModel(
            name='SemenMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida')], max_length=3)),
                ('straws', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('purchase', 'Compra'), ('collection', 'Colecta'), ('insemination', 'Inseminación'), ('sale', 'Venta'), ('discard', 'Descarte'), ('adjustment', 'Ajuste')], max_length=16)),
                ('date', models.DateField()),
                ('source_kind', models.CharField(blank=True, max_length=40)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semen_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='genetics.semenbatch')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['semen_batch', 'date'], name='genetics_se_semen_b_edeff9_idx')],
            },
        ),
    ]
