# Generated by Django 6.0.7 on 2026-07-25 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=8)),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('source', models.CharField(default='manual', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'currency', 'source'],
                'indexes': [models.Index(fields=['currency', '-date'], name='fx_fxrate_currenc_b6932b_idx')],
                'constraints': [models.UniqueConstraint(fields=('currency', 'date', 'source'), name='unique_fx_rate_per_currency_date_source')],
            },
        ),
    ]
