# Generated by Django 5.2.16 on 2026-07-21 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("livestock", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("unit", models.CharField(default="kg", max_length=16)),
                ("category", models.CharField(blank=True, max_length=60)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FeedDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feed_deliveries",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "feed_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="feed.feedtype"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedStockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_kind",
                    models.CharField(
                        choices=[("own", "Feedlot (propio)"), ("client", "Cliente")],
                        max_length=8,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Entrada"), ("out", "Salida")], max_length=3
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                ("source_kind", models.CharField(blank=True, max_length=32)),
                ("source_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feed_stock",
                        to="clients.client",
                    ),
                ),
                (
                    "feed_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="feed.feedtype"
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["owner_kind", "client", "feed_type"],
                        name="feed_feedst_owner_k_fe4307_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FeedingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("client_stock", "Stock del cliente"),
                            ("own_stock", "Stock propio (feedlot)"),
                        ],
                        max_length=12,
                    ),
                ),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "animal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedings",
                        to="livestock.animal",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedings",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feedings",
                        to="livestock.lot",
                    ),
                ),
                (
                    "feed_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="feed.feedtype"
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("animal__isnull", False), ("lot__isnull", True)),
                            models.Q(("animal__isnull", True), ("lot__isnull", False)),
                            _connector="OR",
                        ),
                        name="feeding_target_animal_xor_lot",
                    )
                ],
            },
        ),
    ]
