# Generated by Django 6.0.7 on 2026-07-25 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        ('feedyard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingevent',
            name='pen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedings', to='feedyard.pen'),
        ),
    ]
